import {
  readdirSync,
  statSync,
  readFileSync,
  existsSync,
  mkdirSync,
  writeFileSync,
} from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { format } from "prettier";

const __dirname = dirname(fileURLToPath(import.meta.url));

/** Walk lib/ graph from project root and collect all out/ directories (for artifact lookup of lib-deployed contracts). */
function getLibOutRoots(projectRoot) {
  const roots = [];
  const libDir = join(projectRoot, "lib");
  if (!existsSync(libDir) || !statSync(libDir).isDirectory()) return roots;
  const entries = readdirSync(libDir, { withFileTypes: true });
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    const outPath = join(libDir, e.name, "out");
    if (existsSync(outPath) && statSync(outPath).isDirectory()) {
      roots.push(outPath);
    }
    const nestedLib = join(libDir, e.name, "lib");
    if (existsSync(nestedLib) && statSync(nestedLib).isDirectory()) {
      roots.push(...getLibOutRoots(join(libDir, e.name)));
    }
  }
  return roots;
}

const foundryRoot = join(__dirname, "..");
const libArtifactRoots = getLibOutRoots(foundryRoot);

const generatedContractComment = `
/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */`;

function getDirectories(path) {
  if (!existsSync(path)) {
    return [];
  }

  return readdirSync(path).filter(function (file) {
    return statSync(join(path, file)).isDirectory();
  });
}

function getFiles(path) {
  return readdirSync(path).filter(function (file) {
    return statSync(join(path, file)).isFile();
  });
}

function parseTransactionAndReceiptRun(filePath) {
  try {
    const content = readFileSync(filePath, "utf8");
    const broadcastData = JSON.parse(content);
    return {
      transactions: broadcastData.transactions || [],
      receipts: broadcastData.receipts || [],
    };
  } catch (error) {
    console.warn(`Warning: Could not parse ${filePath}:`, error.message);
    return [];
  }
}

function getDeploymentHistory(broadcastPath) {
  const files = getFiles(broadcastPath);
  const deploymentHistory = new Map();

  // Sort files to process them in chronological order
  const runFiles = files
    .filter(
      (file) =>
        file.startsWith("run-") &&
        file.endsWith(".json") &&
        !file.includes("run-latest")
    )
    .sort((a, b) => {
      // Extract run numbers and compare them
      const runA = parseInt((a.match(/run-(\d+)/) || [])[1] || "0");
      const runB = parseInt((b.match(/run-(\d+)/) || [])[1] || "0");
      return runA - runB;
    });

  for (const file of runFiles) {
    const { transactions, receipts } = parseTransactionAndReceiptRun(
      join(broadcastPath, file)
    );

    for (const tx of transactions) {
      if (tx.transactionType === "CREATE" || tx.transactionType === "CREATE2") {
        // Store or update contract deployment info
        deploymentHistory.set(tx.contractAddress, {
          contractName: tx.contractName,
          address: tx.contractAddress,
          deploymentFile: file,
          transaction: tx,
          receipt: receipts.find((r) => r.transactionHash === tx.hash),
        });
      }
    }
  }

  return Array.from(deploymentHistory.values());
}

function getArtifactOfContract(contractName) {
  const current_path_to_artifacts = join(
    __dirname,
    "..",
    `out/${contractName}.sol`
  );

  if (!existsSync(current_path_to_artifacts)) return null;

  const artifactJson = JSON.parse(
    readFileSync(`${current_path_to_artifacts}/${contractName}.json`)
  );

  return artifactJson;
}

/** Try main out/, then each lib out/, for artifact. Used only when adding missing contracts from deployments JSON. */
function getArtifactOfContractFromAnyPath(contractName) {
  const artifact = getArtifactOfContract(contractName);
  if (artifact) return artifact;
  for (const libRoot of libArtifactRoots) {
    const libPath = join(libRoot, `${contractName}.sol`);
    const libJson = join(libPath, `${contractName}.json`);
    if (existsSync(libJson)) {
      return JSON.parse(readFileSync(libJson));
    }
  }
  return null;
}

function getInheritedFromContracts(artifact) {
  let inheritedFromContracts = [];
  if (artifact && artifact.ast) {
    for (const astNode of artifact.ast.nodes) {
      if (astNode.nodeType == "ContractDefinition") {
        if (astNode.baseContracts.length > 0) {
          inheritedFromContracts = astNode.baseContracts.map(
            ({ baseName }) => baseName.name
          );
        }
      }
    }
  }
  return inheritedFromContracts;
}

function getInheritedFunctions(mainArtifact) {
  const inheritedFromContracts = getInheritedFromContracts(mainArtifact);
  const inheritedFunctions = {};
  for (const inheritanceContractName of inheritedFromContracts) {
    const artifact = getArtifactOfContract(inheritanceContractName);
    if (artifact) {
      const {
        abi,
        ast: { absolutePath },
      } = artifact;
      for (const abiEntry of abi) {
        if (abiEntry.type == "function") {
          inheritedFunctions[abiEntry.name] = absolutePath;
        }
      }
    }
  }
  return inheritedFunctions;
}

function processAllDeployments(broadcastPath) {
  const scriptFolders = getDirectories(broadcastPath);
  const allDeployments = new Map();

  scriptFolders.forEach((scriptFolder) => {
    const scriptPath = join(broadcastPath, scriptFolder);
    const chainFolders = getDirectories(scriptPath);

    chainFolders.forEach((chainId) => {
      const chainPath = join(scriptPath, chainId);
      const deploymentHistory = getDeploymentHistory(chainPath);

      deploymentHistory.forEach((deployment) => {
        const timestamp = parseInt(
          (deployment.deploymentFile.match(/run-(\d+)/) || [])[1] || "0"
        );
        const key = `${chainId}-${deployment.contractName}`;

        // Only update if this deployment is newer
        if (
          !allDeployments.has(key) ||
          timestamp > allDeployments.get(key).timestamp
        ) {
          allDeployments.set(key, {
            ...deployment,
            timestamp,
            chainId,
            deploymentScript: scriptFolder,
            deployedOnBlock: deployment.receipt && deployment.receipt.blockNumber,
          });
        }
      });
    });
  });

  const allContracts = {};

  allDeployments.forEach((deployment) => {
    const { chainId, contractName } = deployment;
    const artifact = getArtifactOfContract(contractName);

    if (artifact) {
      if (!allContracts[chainId]) {
        allContracts[chainId] = {};
      }

      allContracts[chainId][contractName] = {
        address: deployment.address,
        abi: artifact.abi,
        inheritedFunctions: getInheritedFunctions(artifact),
        deploymentFile: deployment.deploymentFile,
        deploymentScript: deployment.deploymentScript,
        deployedOnBlock:
          deployment.deployedOnBlock != null &&
          Number(BigInt(deployment.deployedOnBlock)),
      };
    }
  });

  return allContracts;
}

function main() {
  const current_path_to_broadcast = join(__dirname, "..", "broadcast");
  const current_path_to_deployments = join(__dirname, "..", "deployments");

  const Deploymentchains = getFiles(current_path_to_deployments);
  const deployments = {};

  // Load existing deployments from deployments directory
  Deploymentchains.forEach((chain) => {
    if (!chain.endsWith(".json")) return;
    chain = chain.slice(0, -5);
    var deploymentObject = JSON.parse(
      readFileSync(`${current_path_to_deployments}/${chain}.json`)
    );
    deployments[chain] = deploymentObject;
  });

  // Process all deployments from all script folders
  const allGeneratedContracts = processAllDeployments(
    current_path_to_broadcast
  );

  // Update contract keys based on deployments if they exist
  Object.entries(allGeneratedContracts).forEach(([chainId, contracts]) => {
    Object.entries(contracts).forEach(([contractName, contractData]) => {
      const deployedName = deployments[chainId] && deployments[chainId][contractData.address];
      if (deployedName) {
        // If we have a deployment name, use it instead of the contract name
        allGeneratedContracts[chainId][deployedName] = contractData;
        delete allGeneratedContracts[chainId][contractName];
      }
    });
  });

  // Add contracts from deployments JSON that don't have broadcast entries
  // This handles cases where contracts are deployed via vm.deployCode() or other methods
  Object.entries(deployments).forEach(([chainId, deploymentMap]) => {
    if (!allGeneratedContracts[chainId]) {
      allGeneratedContracts[chainId] = {};
    }

    Object.entries(deploymentMap).forEach(([address, contractName]) => {
      // Skip networkName entry
      if (contractName === "networkName") return;

      // Check if this contract is already in allGeneratedContracts
      const existingContract = Object.values(
        allGeneratedContracts[chainId]
      ).find(
        (contract) =>
          contract.address && contract.address.toLowerCase() === address.toLowerCase()
      );

      if (!existingContract) {
        // Try to find artifact (main out/ then lib out/) for this contract
        const artifact = getArtifactOfContractFromAnyPath(contractName);
        if (artifact) {
          allGeneratedContracts[chainId][contractName] = {
            address: address,
            abi: artifact.abi,
            inheritedFunctions: getInheritedFunctions(artifact),
          };
        }
      }
    });
  });

  const outputDir = process.env.NEXTJS_CONTRACTS_DIR
    ? join(process.env.NEXTJS_CONTRACTS_DIR).replace(/\/?$/, "") + "/"
    : join(__dirname, "..", "..", "nextjs", "contracts") + "/";

  // Ensure target directories exist
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  // Generate the deployedContracts content
  const fileContent = Object.entries(allGeneratedContracts).reduce(
    (content, [chainId, chainConfig]) => {
      const cleanedChainConfig = Object.fromEntries(
        Object.entries(chainConfig).map(([contractName, contractData]) => {
          const { deploymentFile, deploymentScript, ...rest } = contractData;
          return [contractName, rest];
        })
      );
      return `${content}${parseInt(chainId).toFixed(0)}:${JSON.stringify(
        cleanedChainConfig,
        null,
        2
      )},`;
    },
    ""
  );

  // Write the files
  const fileTemplate = (importPath) => `
    ${generatedContractComment}
    import { GenericContractsDeclaration } from "${importPath}";

    const deployedContracts = {${fileContent}} as const;

    export default deployedContracts satisfies GenericContractsDeclaration;
  `;

  writeFileSync(
    `${outputDir}deployedContracts.ts`,
    format(fileTemplate("~~/utils/scaffold-eth/contract"), {
      parser: "typescript",
    })
  );

  console.log(
    `📝 Updated TypeScript contract definition file on ${outputDir}deployedContracts.ts`
  );
}

try {
  main();
} catch (error) {
  console.error("Error:", error);
  process.exitCode = 1;
}
